name: Haxe Workflow [CACHED]

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  
jobs:

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install dependencies
        run: | 
          haxelib install hxcpp
          haxelib install openfl
          haxelib run openfl setup
          haxelib install feathersui

      - name: Restore cache bin
        id: cache-bin-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            bin/linux
            cache
          key: ${{ runner.os }}-cache-bin

      - name: Build project
        run: |
          haxelib run openfl build project.xml linux -DHXCPP_COMPILE_CACHE=cache

      - name: Save cache bin
        id: cache-bin-save
        uses: actions/cache/save@v3
        with:
          path: |
            bin/linux
            cache
          key: ${{ runner.os }}-cache-bin

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: linux-app
          path: bin/linux/bin
          
  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install dependencies
        run: | 
          haxelib install hxcpp
          haxelib install openfl
          haxelib run openfl setup
          haxelib install feathersui
          
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Restore cache bin
        id: cache-bin-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            bin/windows
            cache
          key: ${{ runner.os }}-cache-bin

      - name: Build project
        run: |
          haxelib run openfl build project.xml windows -DHXCPP_COMPILE_CACHE=cache

      - name: Save cache bin
        id: cache-bin-save
        uses: actions/cache/save@v3
        with:
          path: |
            bin/windows
            cache
          key: ${{ runner.os }}-cache-bin

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: windows-app
          path: bin/windows/bin
          
  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install dependencies
        run: | 
          haxelib install hxcpp
          haxelib install openfl
          haxelib run openfl setup
          haxelib install feathersui

      - name: Restore cache bin
        id: cache-bin-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            bin/macos
            cache
          key: ${{ runner.os }}-cache-bin

      - name: Build project
        run: |
          haxelib run openfl build project.xml mac -DHXCPP_COMPILE_CACHE=cache

      - name: Save cache bin
        id: cache-bin-save
        uses: actions/cache/save@v3
        with:
          path: |
            bin/macos
            cache
          key: ${{ runner.os }}-cache-bin
          
      - name: Create pkg
        run: |
          productbuild --component bin/macos/bin/NewHaxeFeathersUIProject.app /Applications ./macos-pkg.pkg

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: macos-pkg
          path: ./macos-pkg.pkg

  release:
    name: Release
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/
          
      - name: Debug
        run: ls -la artifacts

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/linux-app
            artifacts/windows-app
            artifacts/macos-pkg
          draft: true
          prerelease: true
          tag_name: ${{ github.sha }}
          name: ${{ github.sha }}
          body: Some release notes

