name: Draft release
on: workflow_dispatch

jobs:
  build-linux:
    name: Build on Linux
    uses: Aszusz/HelloWorldHaxeGui/.github/workflows/linux.yml@main
    
  build-windows:
    name: Build on Windows
    uses: Aszusz/HelloWorldHaxeGui/.github/workflows/windows.yml@main
    
  build-macos:
    name: Build on MacOS
    uses: Aszusz/HelloWorldHaxeGui/.github/workflows/macos.yml@main
    
  release:
    name: Release
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest

    steps:
    
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release
          draft: true
          files: |
            linux-app/linux-app.tar.gz
            windows-app/windows-app.zip
            macos-pkg/macos-pkg.pkg
