name: Haxe Workflow Windows Demo
  
on:
  workflow_dispatch
  
jobs:
  build:
    name: Build
    runs-on: windows-latest
    
    steps:
      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - run: |
          haxe -version
          haxelib install hxcpp
          
      - uses: actions/checkout@v3
        name: Check out repository

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Run haxe using MSVC
        run: haxe --main Main --cpp cpp
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: assets
          path: cpp/Main.exe
