name: Haxe Workflow Windows Demo
  
on:
  workflow_dispatch
  
jobs:
  build:
    name: Build
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5          

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
      
      - name: Install dependencies
        run: | 
          haxelib install hxcpp
          haxelib install openfl
          haxelib run openfl setup
          haxelib install feathersui
          
      - name: Build project
        run: |
          haxelib run openfl build project.xml windows -clean
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: Installer-win
          path: /bin/windows/bin/NewHaxeFeathersUIProject.exe
